# Generated by Django 4.0 on 2022-05-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youcare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=122)),
                ('last_name', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('date', models.DateTimeField(auto_now=True)),
                ('age', models.CharField(max_length=12)),
                ('dieses', models.CharField(max_length=18)),
                ('address', models.CharField(max_length=18)),
            ],
        ),
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
    ]
