# Generated by Django 3.2 on 2022-06-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youcare', '0003_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientappointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=122)),
                ('last_name', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('date', models.DateTimeField(auto_now=True)),
                ('age', models.CharField(max_length=12)),
                ('dieses', models.CharField(max_length=18)),
                ('address', models.CharField(max_length=18)),
                ('symptoms', models.CharField(max_length=18)),
                ('doctor_name', models.CharField(max_length=18)),
            ],
        ),
        migrations.DeleteModel(
            name='Appointment1',
        ),
    ]
